language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "pip install -r requirements.txt"
  - "git fetch"
  - "git restore -s origin/resources -- tests/testvideo.mp4"
script:
  - python -m pytest tests/